name: Tour Project Pipeline

on:
  push:
    branches:
      - main

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r mlops/requirements.txt

      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HFTOKEN }}
        run: python mlops/data/data_registration.py


  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r mlops/requirements.txt

      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HFTOKEN }}
        run: python mlops/data/data_preparation.py


  model-training:
  needs: data-prep
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: pip install -r mlops/requirements.txt

    - name: Train Model
      env:
        HF_TOKEN: ${{ secrets.HFTOKEN }}
        MLFLOW_TRACKING_URI: file:./mlruns
      run: python mlops/data/train.py


   - name: Model Building
     env:
       HF_TOKEN: ${{ secrets.HFTOKEN }}
    run: python mlops/data/train.py


  deploy-hosting:
    needs:
      - model-training
      - data-prep
      - register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r mlops/requirements.txt

      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HFTOKEN }}
        run: python mlops/hosting/hosting.py
