name: Tour Project Pipeline

on:
  push:
    branches:
      - main  # Automatically triggers on push to the main branch

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r mlops/requirements.txt
      - name: Upload Dataset to Hugging Face Hub
        env:
          HFTOKEN: ${{ secrets.HFTOKEN }}
        run: python mlops/data/data_registration.py

  data-prep:
   needs: register-dataset
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v3
  - name: Install Dependencies
    run:  pip install -r mlops/requirements.txt
  - name: Run Data Preparation
    env:
      HFTOKEN: ${{ secrets.HFTOKEN }}
    run: python mlops/data/data_preparation.py



  model-traning:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r mlops/requirements.txt
      - name: Start MLflow Server
        run: |
          nohup mlflow ui --host 0.0.0.0 --port 5000 &  # Run MLflow UI in the background
          sleep 5  # Wait for a moment to let the server starts
      - name: Model Building
        env:
          HFTOKEN: ${{ secrets.HFTOKEN }}
        run: python mlops/data/train.py


  deploy-hosting:
    runs-on: ubuntu-latest
    needs: [model-traning,data_prepration,registration-dataset]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r mlops/requirements.txt
      - name: Push files to Frontend Hugging Face Space
        env:
          HFTOKEN: ${{ secrets.HFTOKEN }}
        run: python mlops/hosting/hosting.py
